// <auto-generated />
using System;
using DuoLingoKnockOff.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuoLingoKnockOff.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlagImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalChallenges")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "es",
                            Difficulty = "Beginner",
                            FlagImageUrl = "spain.png",
                            Name = "Spanish",
                            TotalChallenges = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "fr",
                            Difficulty = "Beginner",
                            FlagImageUrl = "france.png",
                            Name = "French",
                            TotalChallenges = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "de",
                            Difficulty = "Beginner",
                            FlagImageUrl = "germany.png",
                            Name = "German",
                            TotalChallenges = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "it",
                            Difficulty = "Beginner",
                            FlagImageUrl = "italy.png",
                            Name = "Italian",
                            TotalChallenges = 0
                        });
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsernameCased")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsernameUncased")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.UserProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ChallengeId");

                    b.HasIndex("ChallengeId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.UserStreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStreaks");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.Challenge", b =>
                {
                    b.HasOne("DuoLingoKnockOff.Data.Entities.Language", "Language")
                        .WithMany("Challenges")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.UserProgress", b =>
                {
                    b.HasOne("DuoLingoKnockOff.Data.Entities.Challenge", "Challenge")
                        .WithMany("UserProgresses")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuoLingoKnockOff.Data.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.UserStreak", b =>
                {
                    b.HasOne("DuoLingoKnockOff.Data.Entities.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("DuoLingoKnockOff.Data.Entities.UserStreak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.Challenge", b =>
                {
                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.Language", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("DuoLingoKnockOff.Data.Entities.User", b =>
                {
                    b.Navigation("Progresses");

                    b.Navigation("Streak")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
