/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterDto"];
                    "text/json": components["schemas"]["RegisterDto"];
                    "application/*+json": components["schemas"]["RegisterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/{languageId}/Challenge/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    difficulty?: components["schemas"]["Difficulty"];
                };
                header?: never;
                path: {
                    languageId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChallengeDto"];
                        "application/json": components["schemas"]["ChallengeDto"];
                        "text/json": components["schemas"]["ChallengeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/{languageId}/Challenge/completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    languageId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChallengeDto"][];
                        "application/json": components["schemas"]["ChallengeDto"][];
                        "text/json": components["schemas"]["ChallengeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/{languageId}/Challenge/attempting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    languageId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChallengeDto"][];
                        "application/json": components["schemas"]["ChallengeDto"][];
                        "text/json": components["schemas"]["ChallengeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/{languageId}/Challenge/{challengeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: number;
                    languageId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChallengeUpdateDto"];
                    "text/json": components["schemas"]["ChallengeUpdateDto"];
                    "application/*+json": components["schemas"]["ChallengeUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Language"][];
                        "application/json": components["schemas"]["Language"][];
                        "text/json": components["schemas"]["Language"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Languages/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LeaderboardDto"];
                        "application/json": components["schemas"]["LeaderboardDto"];
                        "text/json": components["schemas"]["LeaderboardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProgressDto"];
                        "application/json": components["schemas"]["UserProgressDto"];
                        "text/json": components["schemas"]["UserProgressDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChallengeDto: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            languageId?: number;
            content?: string | null;
            type?: components["schemas"]["ChallengeType"];
            difficulty?: components["schemas"]["Difficulty"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ChallengeType: 0 | 1 | 2 | 3 | 4;
        ChallengeUpdateDto: {
            isCorrect?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        Difficulty: 0 | 1 | 2;
        Language: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            code?: string | null;
            flagImageUrl?: string | null;
        };
        LanguageProgressDto: {
            /** Format: int32 */
            languageId?: number;
            /** Format: int32 */
            completedChallenges?: number;
            /** Format: int32 */
            totalScore?: number;
        };
        LeaderboardDto: {
            /** Format: int32 */
            languageId?: number;
            entries?: components["schemas"]["LeaderboardEntryDto"][] | null;
            /** Format: int32 */
            currentUserPosition?: number | null;
            currentUserEntry?: components["schemas"]["LeaderboardEntryDto"];
        };
        LeaderboardEntryDto: {
            /** Format: int32 */
            userId?: number;
            username?: string | null;
            usernameCased?: string | null;
            /** Format: int32 */
            totalScore?: number;
            /** Format: int32 */
            completedChallenges?: number;
        };
        LoginDto: {
            username: string;
            password: string;
        };
        RegisterDto: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            preferredLanguage?: string | null;
        };
        UserDto: {
            /** Format: int32 */
            id?: number;
            usernameCased?: string | null;
            username?: string | null;
            token?: string | null;
            preferredLanguage?: string | null;
        };
        UserProgressDto: {
            /** Format: int32 */
            userId?: number;
            languageProgress?: components["schemas"]["LanguageProgressDto"][] | null;
            streak?: components["schemas"]["UserStreakDto"];
        };
        UserStreakDto: {
            /** Format: int32 */
            currentStreak?: number;
            /** Format: int32 */
            maxStreak?: number;
            /** Format: date-time */
            lastSuccessfulAttempt?: string;
            /** Format: date-time */
            currentStreakStartDate?: string;
            /** Format: int32 */
            readonly streakDays?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
